version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 9090:9090
    networks:
      - my-proxy-net
  redis_express:
    image: redis
    command: --port 9999
    ports:
      - "9999:9999"
    networks:
      - my-proxy-net
networks:
  my-proxy-net:
    external:
      name: custom_network