version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db
      - redis
    networks:
      - adonis-proxy-net   
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: provaAdonis
    volumes:
      - /var/lib/mysql56-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - adonis-proxy-net   
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - adonis-proxy-net  
networks:
  adonis-proxy-net:
    external:
      name: custom_network